version: "3.8"

services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=http://13.60.56.112/api/
    command: npm run dev
